//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerConnect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    
    public partial class CheckIn
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BrojCheckIn { get; set; }



        [Required]
        [MaxLength(6)]
        [Display(Name = "Šifra rezervacije")]
        [MinLength(1)]
        public int SifraRezervacije { get; set; }

        [Required]
        [MaxLength(6)]
        [Display(Name = "Broj pasoša")]
        [MinLength(6)]
        public int BrojPasosa { get; set; }

        
        public string Vreme { get; set; }
    
        public virtual Putnik Putnik { get; set; }
    }
}
