//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerConnect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    
    public partial class CheckIn
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BrojCheckIn { get; set; }

        


        [Required(ErrorMessage ="Polje je obavezno!")]        
        [Display(Name = "Šifra rezervacije")]
        [RegularExpression("([0-9]{1,})", ErrorMessage = "Šifra rezervacije mora biti u numeričkom formatu")]
        public int SifraRezervacije { get; set; }

        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Broj pasoša")]
        [RegularExpression("([0-9]{6,10})", ErrorMessage = "Broj pasoša mora biti u numeričkom formatu ******")]
        public int BrojPasosa { get; set; }

        
        public string Vreme { get; set; }
    
        public virtual Putnik Putnik { get; set; }
    }
}
