//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerConnect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ljubimac
    {
        [Display(Name = "Broj čipa")]
        [RegularExpression("([0-9]{6,10})", ErrorMessage = "Broj čipa mora biti u numerickom formatu *******")]
        public int BrojCipa { get; set; }

        [Display(Name = "Broj pasoša")]
        [RegularExpression("([0-9]{6,10})", ErrorMessage = "Broj pasoša mora biti u numerickom formatu *******")]
        public int BrojPasosa { get; set; }

        [Required]
        [Display(Name = "Ime ljubimca")]
        [StringLength(30, ErrorMessage = "Minimalna duzina mora da bude najmanje {2} karaktera dugacka ", MinimumLength = 2)]
        public string Ime { get; set; }

        [Required]
        [Display(Name = "Rasa")]
        [StringLength(30, ErrorMessage = "Minimalna duzina mora da bude najmanje {2} karaktera dugacka ", MinimumLength = 2)]
        public string Rasa { get; set; }

        [Display(Name = "Težina")]
        [RegularExpression("([0-9]{6,10})", ErrorMessage = "Težina ljubimca mora biti u numerickom formatu *******")]
        public int Tezina { get; set; }

        public virtual Putnik Putnik { get; set; }
    }
}