//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerConnect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Zalba
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int SifraZalbe { get; set; }

        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Broj pasoša")]
        [RegularExpression("([0-9]{6,10})", ErrorMessage = "Broj pasoša mora biti u numeričkom formatu ******")]
        public int BrojPasosa { get; set; }

        [Required(ErrorMessage = "Polje je obavezno!")]        
        [Display(Name = "Unesite Vaš komentar")]
        [StringLength(300, ErrorMessage = "Minimalna duzina mora da bude najmanje {2} karaktera dugacka ", MinimumLength = 1)]
        public string Komentar { get; set; }
    
        public virtual Putnik Putnik { get; set; }
    }
}
