//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerConnect
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    
    public partial class CheckIn
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BrojCheckIn { get; set; }

        [Required]
        [MaxLength(30)]
        [Display(Name = "Šifra karte")]
        [MinLength(1)]
        public int SifraKarte { get; set; }

        [Required]
        [MaxLength(6)]
        [Display(Name = "Broj pasoša")]
        [MinLength(6)]
        public int SifraRezervacije { get; set; }
        public int BrojPasosa { get; set; }

        [RegularExpression("[0-9]{2}[:][0-9]{2}",ErrorMessage ="Morate uneti vreme u formatu HH:MM (**:**)")]
        public string Vreme { get; set; }
    
        public virtual Putnik Putnik { get; set; }
    }
}
