//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ljubimac
    {
        public int BrojCipa { get; set; }
        public int BrojPasosa { get; set; }
        public string Ime { get; set; }
        public string Rasa { get; set; }
        public int Tezina { get; set; }
    
        public virtual Putnik Putnik { get; set; }
    }
}
