//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vlasnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vlasnik()
        {
            this.Ljubimacs = new HashSet<Ljubimac>();
        }
    
        public int BrojPasosa { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int BrojTelefona { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ljubimac> Ljubimacs { get; set; }
    }
}
